---
title: "Machine learning I"
author: "Natalia Alonso, Beatriz Visitación y Susana Albarrán"
date: "30/04/2020"
output:
  html_document:
    code_folding: show
    number_sections: yes
    fig_height: 5
    fig_width: 8
    theme: flatly
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
fig_caption: yes
---


```{r, lectura_datos, include=FALSE}
data <- read.csv("hotel_bookings.csv")
```


```{r, setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(ggplot2)

```


# Introducción

<p style = "text-align: justify">

</p>

# Objetivo del estudio

<p style = "text-align: justify">
Predecir el número de reservas mensual.
</p>


# Datos


<p style = "text-align: justify">

</p>

```{r, fig.align='center', warning=FALSE}

date <- data$arrival_date_year

maxima <- max(date)
maxima

minimo <- min(date)
minimo

# summary(data)


data_no_canceled <- data[data$is_canceled == 0,]

dt_month_year_ts <- data_no_canceled %>%
  group_by(arrival_date_month, arrival_date_year) %>% 
  summarise(Recuento = n())


# dt_2016_all$new_date <- as.Date(paste(dt_2016_all$arrival_date_day_of_month, "-", dt_2016_all$arrival_date_month, "-", dt_2016_all$arrival_date_year), c("%d - %B - %Y"), Sys.setlocale("LC_TIME", "English"))


```


```{r}

library(zoo)

dt_month_year_ts$new_date <- as.yearmon(paste(dt_month_year_ts$arrival_date_month, dt_month_year_ts$arrival_date_year, "%b%Y"))

dt_month_year_ts_2016 <- dt_month_year_ts[dt_month_year_ts$arrival_date_year == 2016,] %>%
   arrange(new_date)

tsData <- ts(dt_month_year_ts$Recuento, start = c(2015,7), frequency = 12)
plot(tsData,)

componentes.ts = decompose(tsData)
plot(componentes.ts)



```



<p style = "text-align: justify">

</p>

```{r, fig.align='center', warning=FALSE}


```
