---
title: "Machine learning I"
author: "Natalia Alonso, Beatriz Visitación y Susana Albarrán"
date: "30/04/2020"
output:
  html_document:
    code_folding: show
    number_sections: yes
    fig_height: 5
    fig_width: 8
    theme: flatly
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
fig_caption: yes
---


```{r, lectura_datos, include=FALSE}

data <- read.csv("amazon.csv")

```


```{r, setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(ggplot2)

```


# Introducción

<p style = "text-align: justify">

</p>

# Objetivo del estudio

<p style = "text-align: justify">
Predecir el número de reservas mensual.
</p>


# Datos


<p style = "text-align: justify">

</p>

```{r, fig.align='center', warning=FALSE}

# SUMMARY DE LOS DATOS

date <- as.Date(data$date)

maxima <- max(date)
maxima

minimo <- min(date)
minimo

summary(data)


```


```{r}

# FILTRO POR ESTADO ACRE

library(zoo)

data_acre <- data[data$state == "Acre",]

data_acre <- data_acre %>%
  mutate(month = if_else(month == "Abril", "April", 
                 if_else(month == "Agosto", "August", 
                 if_else(month == "Dezembro", "December", 
                 if_else(month == "Fevereiro", "February", 
                 if_else(month == "Janeiro", "January", 
                 if_else(month == "Julho", "July", 
                 if_else(month == "Junho", "June", 
                 if_else(month == "Maio", "May", 
                 if_else(month == "Setembro", "September", 
                 if_else(month == "Novembro", "November", 
                 if_else(month == "Outubro", "October", "March"))))))))))))

Sys.setlocale ("LC_TIME", 'English')
data_acre$new_date <- as.Date(paste("01", "-", data_acre$month, "-", data_acre$year), c("%d - %B - %Y"))

data_acre_simplif <- data_acre %>% 
  select(number, new_date)


tsData_acre <- ts(data_acre_simplif$new_date, start = c(1998,1), frequency = 12)
plot(tsData_acre,)

componentes_ts = decompose(tsData_acre)
plot(componentes_ts)


```



```{r}

# FILTRO POR ESTADO ACRE Y AÑO 2015

library(zoo)

data_acre_2015_2016 <- data_acre[data_acre$year==2015 | data_acre$year==2016,]

Sys.setlocale ("LC_TIME", 'English')
data_acre_2015_2016$new_date <- as.Date(paste("01", "-", data_acre_2015_2016$month, "-", data_acre_2015_2016$year), c("%d - %B - %Y"))

data_acre_2015_2016_simplif <- data_acre_2015_2016 %>% 
  select(number, new_date)

data_acre_2015_2016_simplif_arrange <- data_acre_2015_2016_simplif %>%
   arrange(new_date)

tsData_2015_2016 <- ts(data_acre_2015_2016_simplif_arrange$number, start = c(2015,1), frequency = 12)
plot(tsData_2015_2016)

plot(data_acre_2015_2016_simplif$number)


```

```{r, fig.align='center', warning=FALSE}

# PRUEBA CON LA LIBRERÍA XTS QUE ES MÁS COMPLETA

library(xts)
library(timeSeries)


x <- timeSeries(data_acre_2015_simplif$number, data_acre_2015_simplif$new_date)

matrix_xts <- as.xts(x)

str(matrix_xts)
plot(matrix_xts[,1])

```

<p style = "text-align: justify">

</p>

```{r, fig.align='center', warning=FALSE}


library("fUnitRoots")

plot(componentes_ts)

urkpssTest(tsData_acre, type = c("tau"), lags = c("short"),use.lag = NULL, doplot = TRUE)
tsstationary = diff(tsData_acre, differences=1)
plot(tsstationary)

acf(tsData_acre,lag.max=140)

ts_seasonally_adjusted <- tsData_acre-componentes_ts$seasonal
tsstationary <- diff(ts_seasonally_adjusted, differences=1)
plot(tsstationary)

acf(tsstationary, lag.max=140)
pacf(tsstationary, lag.max=140)

```



```{r, fig.align='center', warning=FALSE}


```
